name: Rust

on: [push]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build
  #     run: cd fpie && cargo build --verbose
  #   - name: Run tests
  #     run: cd fpie && cargo test --verbose

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./fpie
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - i686-pc-windows-gnu
          - x86_64-apple-darwin	
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./fpie
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cd fpie && cargo test --verbose
# - uses: actions/upload-artifact@v1
#   with:
#     name: my-artifact
#     path: path/to/artifact
