name: Rust

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          # - i686-unknown-linux-gnu
          # - i686-pc-windows-gnu
          # - x86_64-apple-darwin	
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }} --manifest-path ./fpie/Cargo.toml
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./fpie
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --manifest-path ./fpie/Cargo.toml
